---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: roboshop
data:
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deployment
  namespace: roboshop
  labels:
    tier: app
    name: catalogue
spec:
  replicas: {{ .values.deploymentset.replicaCount }}
  selector:
    matchLabels:
      tier: app
      name: catalogue
  template:
    metadata:
      labels:
        tier: app
        name: catalogue
    spec:
      containers:
      - name: catalogue
        imagePullPolicy: Always
        image: "kiranprav/catalogue:{{ .values.deploymentset.imageVersion }}"
        envFrom:
        - configMapRef:
            name: catalogue-config
        ports:
        - containerPort: 8080
