apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    tier: app
    name: catalogue
  ports:
    - protocol: TCP
    
      port: {{ .Values.service.port }}
      targetPort: 8080
